### ISSUE TITLE
Warn using localhost

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1728]
Replicator can not use localhost. So when user is browsing using localhost we should warn them that they should use ip instead.

**Comment by i5o** [comment]
I don't think this is the best approach.. We should find a way to resolve / get the ip of the host.
Mostly because I can set my computer name to `home` and I could access `http://home` and ta-da, the solution wouldn't work.

interesting links: 
- http://net.ipcalf.com/
- https://stackoverflow.com/questions/20194722/can-you-get-a-users-local-lan-ip-address-via-javascript
