### ISSUE TITLE
Record Survey final step: improve header

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#1878]
After `Record survey` it is taking you to profile. should be taken back to survey page

**Comment by paulbert** [comment]
This is intended to record statistics on the person taking the survey, but we should update the header to something better.  Maybe just `Information`.

The "Record Survey" button is more just showing the workflow that will be implemented for the tablets since the web app needs to be connected to the RasPi currently to work.  A user would log in and take the tablet to people to record their survey answers.  At the end of the survey they would have the option of filling out some personal information.
