### ISSUE TITLE
'open file' on resource-view is misleading

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/planet#2024]
In resource-view, it is kind of misleading to have 'open file' for the word, .csv files which are getting downloaded. The download button should be made to work for that purpose.

**Comment by lmmrssa** [comment]
We might want to change the word because download button on top only shows when you choose 'Downloadable' on form. Also it will be blank page if we do not even add Button on resource view. We might want to show some other stuff like image related to file type but that will be other issue and may be to work on later.

For this issue we might want to change text to "Download/Open"

**Comment by BhargaviNadendla** [comment]
@lmmrssa  Do we need to add some styling to the text "Download/Open"(like a button or so) since it is unrecognizable?
