### ISSUE TITLE
Duplicate configuration

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2164]
We are still seeing multiple configuration of same planet code. Its not happening when you try to configuration planet multiple times. Instead it seems like when user press **Submit** multiple times quickly its able to submit multiple request.

**Comment by paulbert** [comment]
This is unrelated to quick clicks.  The configuration added to the nation has a different `_id` than the one on the community, so when that configuration is replicated it adds a second doc rather than updating.  This community was created with the branch on #2198, and the corresponding doc on dev has a different id.

![image](https://user-images.githubusercontent.com/9203229/46121450-bf888e00-c1e1-11e8-97fe-7fecbb7f7cf7.png)

![image](https://user-images.githubusercontent.com/9203229/46121465-cb745000-c1e1-11e8-9bb2-ea00717f832d.png)

**Comment by lmmrssa** [comment]
@paulbert it was also duplicating on dev when doing new setup.
