### ISSUE TITLE
Select All on filtered record not working

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#2183]
After you select all and then do filter on list. Clicking select all does not change the count of selected records
![screen shot 2018-09-25 at 07 12 51](https://user-images.githubusercontent.com/2909490/45987755-fdc36780-c092-11e8-8f17-91d5ea5b316e.png)

If you look on the image I had selected 4 resources and then did filter. When trying to select all or deselect it still shows 4 count

**Comment by paulbert** [comment]
The easy solution is to clear the selection when we update the filter.

A more involved solution would be to check the selected items and remove any that no longer match the filter.  This is a little tricky because it needs to listen for a sort of "filtering complete" event rather than just trigger when the filter changes.

**Comment by jessewashburn** [comment]
This has been fixed. 
[screen-recorder-fri-nov-22-2024-17-35-21.webm](https://github.com/user-attachments/assets/fb2d1626-7df3-4d56-9854-d25315665cf0)
