### ISSUE TITLE
Title property on hover of action links

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2190]
Can we have or not title property on action links ?
right now its only there in Feedback link of Courses, Library,Meetups .
![screenshot from 2018-09-25 07-31-48](https://user-images.githubusercontent.com/27276132/45988222-978c1400-c095-11e8-82e1-0b8b9558865c.png)

Also can we add mat-icon for admin pop-up list ; View Profile, Edit Profile, Change Password, Logout
![screenshot from 2018-09-25 07-32-14](https://user-images.githubusercontent.com/27276132/45988233-a5da3000-c095-11e8-8856-2755970a5893.png)

**Comment by paulbert** [comment]
Title property is most important for links which only have an icon.

I'm not sure that icons in the profile menu will look good, but if someone would like to become familiar with the Material icons then try it out with a PR and we might merge it!

https://material.angular.io/components/icon/overview

**Comment by simily00** [comment]
In relation to this topic. Not sure what the circled icons mean but, onclick they expand to show additional information, so I was thinking a downward arrow instead of the notepad and paper clip? Also, a onhover action that displays "expand"?
![Untitled design](https://user-images.githubusercontent.com/17802123/57048035-65442580-6c27-11e9-9153-1e72d57dc733.png)

**Comment by lmmrssa** [comment]
@simily00 icons are there to notify that it has attachment (resources) exam (test) or survey.
