### ISSUE TITLE
Cannot send survey as non admin

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/planet#2324]
![image](https://user-images.githubusercontent.com/25775298/46809583-60279380-cd34-11e8-886f-5a445a38a2b1.png)

**Comment by dogi** [comment]
somebody needs to confirm this bug

**Comment by nadaa** [comment]
@BhargaviNadendla , I checked on my machine and it works for me!

**Comment by paulbert** [comment]
Send survey will still work for administrator, but it appears for a normal user the `_changes` endpoint is unauthorized.  It's not ideal, but I think for the `_users` database we will need to do a `_find` request every time `getListAndColumns` is called from `DialogsListService`, but the other databases should continue to use the `StateService`.

This can be combined with #2328 into one PR since that will be fixed by requesting every field except those four in the `_find` request.

**Comment by yuviii** [comment]
@BhargaviNadendla @paulbert  can't generate this issue.
