### ISSUE TITLE
In Members list, Add roles is not updating properly

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#2648]
Steps to replicate:
- Add role "Leader", "Learner" to more than 2 members.
- Now select only one role "Leader" from Add roles and click Add roles.

Now its not updating the value.
There is feature to remove the roles from individual list but when updating for bulk it might take time to go through each list and remove.
![screenshot from 2018-12-05 07-22-56](https://user-images.githubusercontent.com/27276132/49484427-2324dc80-f85f-11e8-937a-d35443f7d302.png)

**Comment by paulbert** [comment]
The above is working as intended, but I think you've convinced me that changing it would be better.  Let's try it out where the roles are set to exactly what is selected.

We should change the placeholder text to "Set roles of selected" and "Set roles" for the button since "Add" means in addition to currently set roles.
