### ISSUE TITLE
Disable the submit button when the comment input field is empty

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#2681]
Currently it is posting the empty comment. It would be better to disable button for empty case.

<img width="758" alt="screenshot 2018-12-06 21 05 52" src="https://user-images.githubusercontent.com/6964191/49593101-e4943c80-f99a-11e8-9e6f-b821e8efb9b5.png">

**Comment by paulbert** [comment]
Let's not change the button because I think that will make it confusing for the user.  We should simply not perform the POST to the database if there isn't any change to the rating or the comments.

We have another issue open to clarify this popup to change from two buttons to one button that just says "OK" which I just updated the title of to better reflect this #2192
