### ISSUE TITLE
Resume survey from where taker left off

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#2716]
If someone starts a survey, goes to a different page, and then opens it again they should resume from the question they left off on.

**Comment by jessewashburn** [comment]
It's not that progress doesn't get saved, it's that reopening the survey takes you to the first step, rather than the step you left off on. However, clicking submit will jump you to that step, so clearly both the answer and the current step are saved. Just the navigation is not immediately taking you there. 

For this survey I did questions 1 and 2 but not 3. Reopening the survey takes me to question 1 with my previous answer filled in. 
![image](https://github.com/user-attachments/assets/5335ea5e-5866-4c10-a058-67bfa337b229)

Navigating with arrow right takes me to question 2 with my answer filled in. 
![image](https://github.com/user-attachments/assets/8a090028-3df0-4fce-bddf-80b9e1b3044c)

However, hitting submit from question 1 will take directly me to question 3. This should be the default when reopening the survey. 

![image](https://github.com/user-attachments/assets/e7885eea-cc26-43bd-bf4d-13d2c75028d4)
