### ISSUE TITLE
Members: Setting and removing bug

### ISSUE THREAD

**Issue by BhargaviNadendla** [open-learning-exchange/planet#2858]
https://www.useloom.com/share/a7c1420a79404e7aa177f9a9ef865bf0

**Comment by paulbert** [comment]
A little more detail:

When we set roles on multiple members each member's role property is set to the same roles array.

The simple fix would be in the assignment in the function passed to `subscribe` would be set the roles property like this: `roles: [ ...roles ]` which copies the elements of the roles array rather than pointing to the same variable.
