### ISSUE TITLE
Achievement: Enter an achievement on update gives date console error

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3342]
- Enter an achievement with title & date.
- Do not submit achievements.
- Edit same achievement to add a description.

![screenshot from 2019-03-07 20-14-52](https://user-images.githubusercontent.com/27276132/53964126-d3340b00-4116-11e9-82b5-060407aeda16.png)

**Comment by ArashDai** [comment]
I tried to recreate this issue and i got a different error. 
Steps:
-went to achievements
-hit edit achievements button
-typed in a name and a date
-hit cancel
-hit edit achievements button again
-add a description
-add a birth date
"there was an error updating your achievements"
-press back button since page is now frozen with spinning loader
-go back to achievement page, description is successfully updated, but date is not saved
![achivementissue](https://user-images.githubusercontent.com/8280071/54000735-6eb88200-40fd-11e9-9aad-b6c381fd2d5e.png)
