### ISSUE TITLE
Survey: Handling long titles

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3512]
1. can there be scroll when title of survey is long similar to course description.
![Screenshot from 2019-04-02 07-23-40](https://user-images.githubusercontent.com/27276132/55369958-6e52b180-5518-11e9-8c6d-44ddd10c634c.png)
![Screenshot from 2019-04-02 07-23-14](https://user-images.githubusercontent.com/27276132/55369959-6e52b180-5518-11e9-8277-9644dc2a1f03.png)
2. No of times taken can be made centered align rather than left aligned.

**Comment by paulbert** [comment]
This is a title rather than a description, so it should not be multi line in actual use.

**Comment by paulbert** [comment]
Combining with #3514 because they relate to the same topic.  When the survey title is too long some of the UI elements showing it have problems.  I'll reiterate this is low priority since in normal use the survey title should not need to be very long:
![image](https://user-images.githubusercontent.com/9203229/55372909-53a91a00-54d1-11e9-8a46-41340d74b29d.png)
