### ISSUE TITLE
Survey: Need some kind of label or indication for the survey that is attached to courses.

### ISSUE THREAD

**Issue by yuviii** [open-learning-exchange/planet#3564]

**Comment by yuviii** [comment]
I think it would be better to add link to survey if attached in course detail as well.

<img width="719" alt="Screenshot 2019-04-09 07 58 57" src="https://user-images.githubusercontent.com/6964191/55768680-8dfc5380-5a9d-11e9-9481-0bd224bfd687.png">

**Comment by paulbert** [comment]
For the course view we'll make that a separate issue.  This issue is for having an indication on the SurveysComponent list which courses the survey is attached to, if any.

**Comment by lmmrssa** [comment]
@yuviii Adding button that takes you to related course would be good enough. As course title could be long we don't want that column to take lot of space.

**Comment by paulbert** [comment]
Hmm I disagree. I think we should have the course title viewable. Otherwise to see the title you have to click on each button and remember which is which. Not very user friendly. The title should still link to the course detail page.

We can limit the length the title takes up with text-overflow for that cell:
https://css-tricks.com/almanac/properties/t/text-overflow/
