### ISSUE TITLE
mySurvey: count of mySurvey mismatch with the Pending request

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#3693]
![Screenshot from 2019-04-25 21-29-34](https://user-images.githubusercontent.com/27276132/56749370-5251d100-67a1-11e9-9d05-e02255524ea0.png)
![Screenshot from 2019-04-25 21-29-25](https://user-images.githubusercontent.com/27276132/56749372-5251d100-67a1-11e9-89cc-56edcc54a2c8.png)
even though there is no Pending request in mySurvey List, count still showing 3

**Comment by paulbert** [comment]
This is due to taking a survey twice in a course.

Similar to when a survey is sent to a learner, we should only have one submission for the survey per revision.  So when the learner tries to take a survey a second time we should use the first submission document and edit those answers rather than creating a new submission document.

**Comment by paulbert** [comment]
@YuserahN Let me know if you have any questions about this, but I think this would be a good next issue for you.

**Comment by YuserahN** [comment]
@paulbert @singharpita I've taken surveys multiple times in a course and I am still not having this problem. The count for mySurveys is the same as the number of pending surveys, for me. Can someone detail the steps to recreate this issue?

**Comment by paulbert** [comment]
@YuserahN Ok, the missing detail is that the second or last time you take the survey leave it incomplete.  The `mySurveys` list will show a 1 (or +1 whatever it was before) which is supposed to denote a pending survey, but that pending survey will not show up in the list because the list is filtered to only one submission per survey.

Regardless of the confusion in the UI, each time you take a survey from a course a new submission document is created if the all previous ones are complete.  This is different from other cases of taking a survey, where answers from previous submissions are overwritten.
