### ISSUE TITLE
ExamsAdd: Remove exam title

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#3700]
We should generate a title for the exam based on the course title (whatever has been inputted at that time).

If there is no title yet, lets just call it `Exam {number}`.

Not ideal if we want to have exam management outside of courses in the future, but since we don't use that field now we have a request to remove it.

**Comment by YuserahN** [comment]
@paulbert Does this mean we should remove the Save button that is displayed below? Because all it does is save the exam title. But since we're removing that field altogether, should just be left with Return and Add Question?

![add_exam](https://user-images.githubusercontent.com/21087353/56918103-c5e62d80-6a82-11e9-807d-af7f54114c21.PNG)

**Comment by YuserahN** [comment]
@paulbert Should the exam title field be removed entirely? Or should the exam title input field display the course title, with/without the option to change it?

**Comment by YuserahN** [comment]
@paulbert By ```Exam {number}```, are you referring to the overall number of the exam? Or the number of the exam within the course (which would also be the same as the step number)?
