### ISSUE TITLE
Should Course Progress Bar Be Reset Upon Retaking Exam

### ISSUE THREAD

**Issue by YuserahN** [open-learning-exchange/planet#3832]
When an exam is graded, the progress bar is updated. (It's set to green.) If the user retakes the exam, it should reset to blue while it awaits grading once again.

**Comment by paulbert** [comment]
Closing since once a learner has passed, we allow them to retake an exam for review.  It doesn't count for their passing status.

The only thing I could see changing is adding a function for course leaders/administrators to reset a passing grade to make a learner retake an exam to pass.  We've got a lot more to get through before we think about adding something like that, though.
