### ISSUE TITLE
Configuration: minor wording of Submit

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4172]
![image](https://user-images.githubusercontent.com/22685147/60476047-0c553580-9c48-11e9-98ae-71ac3f42740d.png)

I'm just not used to using the word "Submit" for updating configuration. I'd recommend "Update" instead.

**Comment by paulbert** [comment]
Since this is the same component as the one used for creating the configuration, make sure to have the button text dynamically set based on which version of the component is being used.

Bonus if you use the Angular i18n select syntax:
https://angular.io/guide/i18n#select-among-alternative-text-messages
