### ISSUE TITLE
Right tile contents of team could be more compact

### ISSUE THREAD

**Issue by Liew211** [open-learning-exchange/planet#4247]
![image](https://user-images.githubusercontent.com/43839884/60854609-e3e0b480-a1ce-11e9-98e1-5ac641f7e4f0.png)
I think the visit count here isn't necessary, and all of the buttons can be on the same line as the name.

**Comment by paulbert** [comment]
Here's a few thoughts:
- Looking at this now, I think we can remove the View Profile button since clicking the name will route to the profile.
- I also think we could show multiple cards per row.  We could use CSS grid to create this layout in a responsive way.
- Unfortunately visit count is a specific request & we can't remove it
