### ISSUE TITLE
TeamsView: Broken template for connected team

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#4386]
It happens when there are no member showing. May be it is related to #4385 
Additional NOTE: It was seen for team connected to Nation

**Comment by paulbert** [comment]
Different issue, but the fix for #4385 will at least fix the breaking part of this.

This issue is because the `member.userDoc` property is only filled by the matching document in the `_users` database, so when trying to access `member.userDoc.firstName` for members of external Planets an error is thrown breaking the template.

Long term we would want to also look up the corresponding doc in `parent_users` or `child_users`, but for now fixing the breaking change is fine.
