### ISSUE TITLE
Submission/mySurvey: "Not found" message should display when blank

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#4391]
when there is no data or list is empty, 
in case of Tests, "No Test found"
in case of Surveys, "No Survey found"
in case of mySurveys, " No mySurvey found"
![Screenshot from 2019-07-23 07-10-35](https://user-images.githubusercontent.com/27276132/61675758-55fde100-ad19-11e9-990a-c6676c7767d9.png)
![Screenshot from 2019-07-23 07-10-49](https://user-images.githubusercontent.com/27276132/61675760-56967780-ad19-11e9-93e5-2529379020df.png)

**Comment by paulbert** [comment]
The changing view has been implemented for both Submissions and mySurveys to show when no items were found from the database (see image below for mySurveys).  The issue is that there are new cases where we could consider showing them.

**For Submissions**
1. Now that this view begins filtered, we could show the message any time the filter ends up with 0 results.
2. We could also hide the "Tests/Surveys" button switch if only one exists.  Or only show the one that exists so the label is there.

Let's start with the first and we can decide later if we want to do the second.

![image](https://user-images.githubusercontent.com/9203229/61679528-7d7e8a80-acd4-11e9-88c1-b379df781730.png)
