### ISSUE TITLE
Team: My Tasks tab

### ISSUE THREAD

**Issue by sjson421** [open-learning-exchange/planet#4641]
There should be an additional tab that shows specific tasks assigned to a particular member.

**Comment by paulbert** [comment]
Rather than an additional tab I'd lean towards a filter option in the tasks tab.  Leader should default to showing all tasks, while other members should default to showing their own.

A couple of options for that switch.
https://material.angular.io/components/button-toggle/overview
https://material.angular.io/components/slide-toggle/overview
