### ISSUE TITLE
Looks like everytime docker is started it looses myplanet version file.

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5261]

**Comment by paulbert** [comment]
Just tested a little more, I think it is only happening after the upgrade.

This makes sense because it is a new container, but we only write the myplanet version after downloading a new apk.

I think this would be fixed by adding a volume so the version number is saved directly on the host machine and will survive the upgrade.

**Comment by lmmrssa** [comment]
add `/usr/share/nginx/html/apkversion` and mount it on volumes.yml file. Tested on one of server and working good.
