### ISSUE TITLE
Opening resource link directly does not work.

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5277]
Link of resource trying to open on browser will take you to library page

**Comment by paulbert** [comment]
@lmmrssa What link exactly are you clicking?  Is this a problem with all of the links to a resource?

This is not enough detail for an issue.

**Comment by paulbert** [comment]
@dogi explained this to me in the meeting today.

The issue is that attempting to open a resource by pasting its URL into the browser is not working on Planet Somalia.

After having a chance to think about it, it looks like the links are for resources that are not found in the first batch of 1000 retrieved from the database, and the component is rerouting because of that.
