### ISSUE TITLE
hub community not filtered on community list

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#5433]
When community is treated as hub it should not show up under list of communities.

**Comment by paulbert** [comment]
To clarify (since it took me a second to figure out what this was referring to) on the nation a hub is still in the list of the communities in "Manage Communities" and it should not be.

In the below **test158** is **Paul Test Hub 2** but it is still in the list:
![image](https://user-images.githubusercontent.com/9203229/71592401-0dcfbf80-2afe-11ea-97e4-760498ebcbf4.png)
