### ISSUE TITLE
Export CSV not working when assigning DOB to recorded survey profile user

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5509]
- record a survey
- in update user profile, update the dob
- now export CSV
![Screenshot from 2020-01-09 20-46-00](https://user-images.githubusercontent.com/27276132/72078665-9ed64000-3321-11ea-860a-97c8b2f4c03a.png)

**Comment by paulbert** [comment]
I tested with a normal user with a DOB filled out.  That also triggers this error.

The error is because every field in the CSV is parsed for markdown elements to be removed.  The DOB is converted into an age as a number, and the markdown parser tries to use a string method on that number which throws the error.
