### ISSUE TITLE
In Dashboard, Courses-Myprogress redirects to "Sorry Page not found" 

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5634]
![Screenshot from 2020-01-28 08-04-43](https://user-images.githubusercontent.com/27276132/73230339-f5a69b00-41a4-11ea-8cda-cdb81d35298f.png)

**Comment by paulbert** [comment]
The correct route as it stands is `/courses/myProgress`.  Let's change so that the button routes to static url/route rather than relative.

There is a temptation to change it to `/myDashboard/courses/progress` and then update how the route structure works, but I think we should just fix the link first.
