### ISSUE TITLE
Teams: task header UI inconsistency

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5686]
header "**task**" is not consistent when comparing with team leader and others members.
also top margin would be better in case of other members.
![Screenshot from 2020-02-04 08-49-43](https://user-images.githubusercontent.com/27276132/73710358-d7ecaf00-472b-11ea-9bbd-0f0bde187c66.png)

**Comment by paulbert** [comment]
Highlighting the **Tasks** subheaders for this issue.  It would be good to have them aligned at the same height in each card.

![73710358-d7ecaf00-472b-11ea-9bbd-0f0bde187c66](https://user-images.githubusercontent.com/9203229/73713023-e8743980-46d9-11ea-9982-2c9c5943351a.png)

**Comment by paulbert** [comment]
I'm going to close this issue.  If it was a quick fix it would be fine, but the simple solution breaks a lot of the UI for this page.

It's more important that all of the information is viewable, and because the subheaders vary in height let's just allow for **Tasks** to appear at different heights.
