### ISSUE TITLE
News: Label list & share button status update after change

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5814]
- add all the given labels
- link doesn't get disabled (until page refresh)
![Screenshot from 2020-02-20 20-00-03](https://user-images.githubusercontent.com/27276132/74941711-9d695e80-541b-11ea-8abd-970ef962c9a6.png)

- remove one of the labels
- Add label button doesn't get enabled(until page refresh)
![Screenshot from 2020-02-20 19-57-16](https://user-images.githubusercontent.com/27276132/74941682-8aef2500-541b-11ea-878e-67a002815412.png)

Also, because of page refresh problem, labels in list keep showing even though already added.
![Screenshot from 2020-02-20 20-09-01](https://user-images.githubusercontent.com/27276132/74943912-44022f00-541d-11ea-84ea-deb5799d8dd0.png)

**Comment by paulbert** [comment]
I would also include that the "Share with Community" button is not removed after clicking in a Team or Enterprise.  It should be because there is nowhere else to share it with at that point.

Both have nearly the same solution: setting `this.showShare` and `this.labels.listed` should be moved from `ngOnInit` into `ngOnChanges` because the component is no longer destroyed and recreated when the news is updated.
