### ISSUE TITLE
Reply is not shared to the community

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5816]
- Create a post in team/enterprise
- add reply
- now try to share reply to community
- success message shown but it doesn't get added
- Also no shareable button/link shown on Main conversation/message

![Screenshot from 2020-02-20 20-16-36](https://user-images.githubusercontent.com/27276132/74944448-297c8580-541e-11ea-808f-efef7bd46693.png)

**Comment by paulbert** [comment]
Need to discuss possible next steps:

1. Don't allow replies to be shared at all
2. Share all replies when a message is shared.  Will also need to update so that when a new reply is written it shows up in all places the main message is shown.
3. Only show "Share with Community" for a reply if the root message is already shared.

**Comment by lmmrssa** [comment]
Based on broader meeting, we will show **Share with Community** on each reply and it will not be automatically shared along with message it was replied for.
We can implement option `#3` so that reply will only have share with community if its root message is already shared with community
