### ISSUE TITLE
Certification: course link result in "No Page found" error

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#5822]
![Screenshot from 2020-02-20 20-52-01](https://user-images.githubusercontent.com/27276132/74947408-ea9cfe80-5422-11ea-90aa-c10d4d9d8070.png)

**Comment by lmmrssa** [comment]
Issue is when clicking on course inside certificate

**Comment by paulbert** [comment]
Issue is present in both **CertificationsViewComponent** and **CertificationsAddComponent**.

I think ideally course information would open in a dialog, especially in **CertificationsAddComponent** where we could lose work that was not saved for creating the certification.

The simpler solution would be to make that an absolute instead of relative link.

**Comment by paulbert** [comment]
Also for the simpler solution we could open it in a new tab, similar to when `isDialog` is set.
