### ISSUE TITLE
CourseView: Error if exam not in database

### ISSUE THREAD

**Issue by robinGiri** [open-learning-exchange/planet#5939]
In course view when we have taken course we have a feature which lets us preview our test. But if we haven't taken our test then it lets us preview the course but after we press next button it gives console error. 

![Screenshot from 2020-03-10 16-39-54](https://user-images.githubusercontent.com/45058288/76305731-cf206780-62ed-11ea-92e9-4d01d56c51ca.png)

**Comment by paulbert** [comment]
The error is that the test is not found in the `exams` database to preview.  You can still take this test in the course because it is also embedded in the course document, but for preview mode to make it work for surveys we use the `exams` database.

@robinGiri Was this test on a course that you replicated from Planet Dev?

**Comment by robinGiri** [comment]
Yes, @paulbert it was in Planet Dev.

**Comment by paulbert** [comment]
Fixed in #6585
