### ISSUE TITLE
Notification for new user does not show user if user profile updated

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6194]
If notification has been created without user profile updated and later on updated profile, then when you click on notification for user created it will show empty record as user name has already been updated and name might be different than username

**Comment by paulbert** [comment]
@lmmrssa This is an issue where an image would be helpful.  The notification for a new member links to the members list with the username in the search field (pictured below).

I think linking directly to the user profile page would be better because that link is based on the username which does not change. That route would be `/manager/users/profile/{username}`.

![image](https://user-images.githubusercontent.com/9203229/80173264-46b80680-85bd-11ea-88b3-ea3679de0041.png)
