### ISSUE TITLE
minDate of report is right now taken based on userlogin of nonadmin

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6306]
Right now min date for report is based on nonadmin first login. It will be good to use community setup date as mindate

**Comment by paulbert** [comment]
@lmmrssa It's based on the oldest login, regardless of who logged in.  Since none of the other activities can take place without a login, do we need to change this?

**Comment by paulbert** [comment]
Oh I misread that and missed the _non_.  Right since we filter the first admin out their login will not be included.

But still, most of their information should be filtered out anyway, so the dates before what we're showing now should not have data.

I'm going to close this.  I don't think it would be good to have the minimum date before there is any actual data and using the community setup date could do that.
