### ISSUE TITLE
Edit profile page space between buttons

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6309]
There's no space between the _Submit_ and _Cancel_ buttons. Should we add space between them?

Also, in the Edit Profile page the svg icons for male and female aren't the same size. Should that be fixed as well?

![Annotation 2020-05-14 084836](https://user-images.githubusercontent.com/54686871/81943356-ca787800-95ea-11ea-9b1a-f2f8b95ac8f9.png)

**Comment by paulbert** [comment]
@Mutugiii Please use the reusable `.action-buttons` class on the container element for the buttons

**Comment by paulbert** [comment]
@jsschf Thanks for writing the issue.  As a general rule please try to avoid tacking on a second thought ("Also" is a red flag for this) because a tangent can get lost in an issue.  It's better to make a new issue.

For the svgs, it looks like there's a pixel or two missing at the bottom for the male one, but they are sized the same from our end.  I don't think we need to worry about that. 

![image](https://user-images.githubusercontent.com/9203229/82007754-fd495d00-9638-11ea-95b8-6cac036fe21c.png)

![image](https://user-images.githubusercontent.com/9203229/82007786-13efb400-9639-11ea-96c2-caa50ea56edc.png)

**Comment by Mutugiii** [comment]
@paulbert Thanks, I will do so.

**Comment by jsschf** [comment]
@paulbert I wasn't sure how to write up small UI issues on the same page, but thanks for informing me! I'll make separate issues next time.
