### ISSUE TITLE
Myhealth: add examination styling

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6313]
+ There is little space between the group of checkboxes and the first textbox, making it easy to miss the label "Observation & Notes".
+ The labels (diagnosis, observation & notes, diagnosis, etc) are small, and in the case of the checkbox area is smaller than the text for each checkbox.
+ There is a duplicate label _Diagnosis_ above the checkbox area and in the second textbox
![Annotation 2020-05-14 091228](https://user-images.githubusercontent.com/54686871/81946812-5e4c4300-95ef-11ea-8873-71165d89aff9.png)

**Comment by paulbert** [comment]
@jsschf Please only add the additional spacing between the checkboxes and **Observations & Notes** for an initial PR.  We can maybe include handling the **Diagnosis** labels in this, but I need to check with the larger team about what to do with that.

The labels & textbox are all in a reusable component.  The labels match the labels for input fields.  Since this would be site wide we should make sure any changes to that make sense across the site, meaning those changes should be in a separate PR so it doesn't hold up fixing the form spacing.

**Comment by jsschf** [comment]
@paulbert Will do!
