### ISSUE TITLE
HealthEvent: Zero values allowed for validated fields

### ISSUE THREAD

**Issue by chtelmko** [open-learning-exchange/planet#6337]
Problem:
Under the Condition and Treatment. When you select zero for pulse it doesn't show up in the warning pop up.

Screenshots:
![my health pulse= 0  its not shown as an error](https://user-images.githubusercontent.com/40531136/82275314-6b02cb00-9950-11ea-8cd0-26c322438172.png)

**Comment by paulbert** [comment]
Good catch.  Line 106 should have `value === null || value === ''` instead of `!value`

**Comment by paulbert** [comment]
Editing the title to reflect the issue.  The dialog should not include values < 1 because that should be stopped by validation.

**Comment by paulbert** [comment]
Removing **Newbie Friendly** because I think this is more complicated after the introduction of the rounded values.

**Comment by jsschf** [comment]
So this works to prevent the form from being submitted without the warning popping up: 

> 
> 
> Good catch. Line 106 should have `value === null || value === ''` instead of `!value`

However, in the _Examinations_ it still shows an empty string as the recorded value.
![Annotation 2020-05-27 135621](https://user-images.githubusercontent.com/54686871/83061036-dda83080-a04b-11ea-931e-ef4a59de83d1.png)

Should I try and find a way to get it to record as zero rather than it getting converted into an empty string?
