### ISSUE TITLE
Exam review multiple choices

### ISSUE THREAD

**Issue by lmmrssa** [open-learning-exchange/planet#6366]
When doing review of exam submissions, we can even change Correct answer of multiple choices to incorrect. And once someone change it, its difficult to check with available choices. 
So may be we either disable changing correct/incorrect for multiple choices
Or show available choices of questions on review page.

**Comment by paulbert** [comment]
I think we can disable the radio buttons for that, so the person can see that the answer is correct but not change it because it is automatically graded.

See video for getting to submission grading.  The component is the same as for taking a test, **ExamsViewComponent**.  The radio buttons should be disabled if the question type is `select` or `selectMultiple`.

https://www.loom.com/share/33da6c276d084bf79ffc5c8cbb635fa5

**Comment by jsschf** [comment]
@paulbert So are you wanting it disabled or not populated on the page? My first thoughts for the fix would be to use *ngIf and not show the radio buttons if they are the `select` or `selectMultiple` type and do an action accordingly.

**Comment by jsschf** [comment]
@paulbert When I said disabled I meant like still visible to the user but greyed out.

**Comment by paulbert** [comment]
@jsschf Yes, there's a `[disabled]` attribute for the radio buttons that can be set so it is still shown to the user but greyed out and the functionality is disabled.

**Comment by jsschf** [comment]
@paulbert Ok thanks
