### ISSUE TITLE
CoursesStepView: Learner can't see grade in "Review Attempts"

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#6459]
### Current Behavior

The "Review Attempts" view for a test has the grade disappear quickly from the screen

### Desired Behavior

The grade should be shown for each question in this view.  Note this view uses  **ExamsViewComponent**.

![image](https://user-images.githubusercontent.com/9203229/83477980-a4642c00-a462-11ea-9c62-cb38d80fda61.png)

**Comment by chtelmko** [comment]
I am not sure what is the best way to approach this issue. After looking through Exams-View-Component.html to see what controls if the grade is shown or if it is hidden in the Review attempts. I have found, that the grade is only shown if it is equal to '1' or '0' ( *ngIf statement, line 59-63). Where "grade===1" is Correct and "grade===0" is Incorrect.
This means that the questions with a multiple choice answers do show a grade:
![multiple choice multiple answer](https://user-images.githubusercontent.com/40531136/83990275-0fa47700-a917-11ea-9ec3-a1cd8d134d40.png)
Because they have an answer that is set when creating a test:
![setting the correct answer](https://user-images.githubusercontent.com/40531136/83990478-d7e9ff00-a917-11ea-9869-7a369d8be70b.png)
Therefore, in these type of questions the grade has a value of either "1" or "0". But in other type of questions the grade is "undefined" and the grade is not shown:
![short answer](https://user-images.githubusercontent.com/40531136/83990984-627f2e00-a919-11ea-9e19-add6b956ad0a.png)

Is there a different way, short and long answer questions should be evaluated to see if they are "correct" or "incorrect" ?

**Comment by paulbert** [comment]
Thanks, I can't replicate the issue anymore on v0.11.10, so I'll close this.
