### ISSUE TITLE
Health: Add examination route consistency after 5 minute

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6597]
- Add an examination
- edit the above examination
- leave the edit page open for more than 5 minutes.
Case 1: Refresh the edit url . It will show message, Examination no longer be edited.

Case 2: Dont refresh the url. Made some changes to the Edit form and click on submit
Changes takes place without any warning message.

Is this functionality consistent??

**Comment by lmmrssa** [comment]
This seems to be related to #6596 We should redirect when someone tries to save or click something after 5 minutes.

**Comment by paulbert** [comment]
1. Since the page can be reached with the url at any time, we want to redirect when the edit page loads beyond the 5 minutes allowed for editing.
2. Once the page is opened, we want to allow the examination to be edited as long as the session is open.  This could take some time, taking it beyond the 5 minute limit.  The limit is just for starting the editing process, not completion.

Closing since this is desired behavior.
