### ISSUE TITLE
DialogsAddTable/Courses: indicate when no courses are available

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#6733]
Could we replicate a fix like [this](https://github.com/open-learning-exchange/planet/pull/6718#issue-442972820) that fixes #6622 in the courses dialog table as well?

Also, we could replicate the same fix on other dialogs like in teams, we have add resources as well

![oleaddfix](https://user-images.githubusercontent.com/48474421/86368978-83bc0b80-bc86-11ea-9722-e2765f4fe38d.png)

**Comment by paulbert** [comment]
Looks like that has already been implemented for Resources & Courses. Closing.

**Comment by paulbert** [comment]
Misunderstood.  This is asking if we should add the message when there are resources or courses available, but the search text doesn't match any of them.

I think we may need to use something other than `*ngIf` to hide the table instead of destroying it or maybe there's an option on `*ngIf` for this.
