### ISSUE TITLE
mySubmissions: Initial columns incorrect

### ISSUE THREAD

**Issue by singharpita** [open-learning-exchange/planet#6816]
Graded on column is hidden for My Sumbission -> Survey.
1.But Go to Survey tab -> click on any survey detail page -> back
2. now graded on column start showing in Survey tab as well.
3. switch to Test tab and then switch back to Survey
4. Now graded on column disappears.

https://recordit.co/7SUu6fT3tA

**Comment by paulbert** [comment]
When it opens as in **Test** view the columns shown is also incorrect.  The **Grade** column is missing, but changing the filter brings it back (see video below).

The `onFilterChange` method should be used to set `this.filter.type` instead of setting that value directly.  This will also set the columns.

https://www.loom.com/share/c574139fae804cff90132c6805b2a1b2

**Comment by Haoran-Hu** [comment]
@paulbert What do you mean by "setting that value directly"?

**Comment by paulbert** [comment]
@Haoran-Hu **SubmissionsComponent** line 62 `this.filter.type` is assigned a value, but we should call `onFilterChange` instead.
