### ISSUE TITLE
Courses: Add autocomplete for "Language"

### ISSUE THREAD

**Issue by jsschf** [open-learning-exchange/planet#6847]
Should the _Language of Instruction_ field have a drop down similar to the profile page? 

![Annotation 2020-07-16 084728](https://user-images.githubusercontent.com/54686871/87678903-0787f480-c76b-11ea-8eb9-71ea5149f3b4.png)

**Comment by paulbert** [comment]
We'd like to allow the user's to submit courses & resources in any language, not just the ones supported for translation in the app.  Practically it's easier to allow anything to be typed in rather than to research various smaller languages spoken in regions where we deploy.

We could add autocomplete to the field so the languages supported for translation show up in a list below the field when typing to help avoid misspelling the languages supported in the app.

**Comment by paulbert** [comment]
Material docs for v8 autocomplete (may be the same as v10, but just in case since we haven't upgraded yet):

https://v8.material.angular.io/components/autocomplete/overview
