### ISSUE TITLE
submissions: table responsiveness

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7630]
Responsiveness options for the submissions table.

![image](https://github.com/user-attachments/assets/ead8a3d3-0546-4b1e-89c6-aa39b5e137ca)

**Comment by RheuX** [comment]
![image](https://github.com/user-attachments/assets/7b6deddb-9a35-4ca1-a738-dbf70fa6059e)

Mine looks like this when its on a small screen. Is there a way to change it? Regardless I was going to change it so that it would still hold the table, but enable horizontal scrolling.

Or it would be something similar like in my current picture, just add more information the left side since just looking at it is kind of confusing.
