### ISSUE TITLE
communal challenge upgrades

### ISSUE THREAD

**Issue by Mutugiii** [open-learning-exchange/planet#7712]
The challenge has 5 key areas.
- Personal challenge: Completing individual requirements(Join Course, Fill Survey, Add Voice)
- Group Challenge: Money goal(each valid challenge submission is $1, max that can be gained is $500)
- Challenge Workflow: The chalenge should appear once on login and be triggered from a specific point(e.g a constant notificatin) 
- Challenge Success: Post challenge completion Message and workflow
- Elasticity: Implementing current implementation to support future challenges. i.e adding challenges support in the db

**Comment by jessewashburn** [comment]
Working on this: "Challenge Workflow: The chalenge should appear once on login and be triggered from a specific point(e.g a constant notificatin)"

**Comment by jessewashburn** [comment]
Feel free to review my draft PR: #7714

**Comment by RheuX** [comment]
I'll probably take a look at the Group Challenge.

Though I do have some points that may can be implemented (could be discussed)
- For the each goals, should probably direct them using a button (not just for the joining course, but also for the survey and voices), so that they dont have to navigate that much.
- If we're going to be do future challenges, it would be great to have all past, present, future challenges listed in a tab.
- **ill add more later**
