### ISSUE TITLE
Add material badge to notification icon

### ISSUE THREAD

**Issue by paulbert** [open-learning-exchange/planet#995]
https://material.angular.io/components/badge/overview

**Comment by Tille88** [comment]
Looked into this, and it will have to wait until Angular 6 is used, since the badges are only available in Angular Material 6

5.2.4:
![screen shot 2018-05-19 at 12 50 40 pm](https://user-images.githubusercontent.com/16757941/40265495-79c45438-5b63-11e8-98ef-39b2bec7bfcc.png)

6.0.1:
![screen shot 2018-05-19 at 12 50 57 pm](https://user-images.githubusercontent.com/16757941/40265498-84c1cb54-5b63-11e8-82d6-1d1b0ec17325.png)

I kept getting this error if trying to use that before Angular 6 update is complete:
https://stackoverflow.com/questions/49899641/type-elementref-is-not-generic
